version: 0.2        
phases:

  pre_build:
    commands:
      - echo "Entered pre-build phase"
      - echo "Wait for a while"
  build:
    commands:
      - echo "Entered build phase"
      - mvn clean package
      - pwd
      - ls -l target
      - cp target/mcms-webapp-0.0.1.war .
      - ls
  post_build:
    commands:
      - echo "Entered the Post build"

artifacts:
  files:
    - target/**/*
 