version: 0.2        
phases:

  pre_build:
    commands:
      - echo "Entered pre-build phase"
      - echo "Wait for a while"
  build:
    commands:
      - echo "Entered build phase"
      - mvn clean package
      - pwd
      - cp -R target/* .
      - mv mcms-webapp-0.0.1 mcms-webapp
      - mv mcms-webapp-0.0.1.war mcms-webapp.war
      - ls -l
  post_build:
    commands:
      - echo "Entered the Post build"

artifacts:
  files:
    - mcms-webapp.war
    - maven-archiver
    - mcms-webapp
 